# Generated by Django 4.2.7 on 2023-11-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_data.usage')),
            ],
        ),
        migrations.CreateModel(
            name='List_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_data.station')),
            ],
        ),
    ]
