# Generated by Django 4.2.7 on 2023-11-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(verbose_name='대여소 번호')),
                ('station_name', models.CharField(max_length=200, verbose_name='대여소명')),
                ('location', models.CharField(max_length=200, verbose_name='자치구')),
                ('addr1', models.CharField(max_length=200, verbose_name='주소1')),
                ('addr2', models.CharField(max_length=200, verbose_name='주소2')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='경도')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_count', models.IntegerField(verbose_name='이용량')),
                ('use_date', models.DateField(verbose_name='대여날짜')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bike_data.station')),
            ],
        ),
    ]
