# Generated by Django 4.2.7 on 2023-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('station_name', models.CharField(max_length=255)),
                ('use_ym', models.CharField(max_length=6)),
                ('rental_count', models.IntegerField()),
                ('return_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=11, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=11, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(unique=True, verbose_name='대여소 번호'),
        ),
    ]
