# Generated by Django 4.2.7 on 2023-11-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='addr2',
            field=models.CharField(max_length=200, null=True, verbose_name='주소2'),
        ),
    ]
